<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>Orders List</title>
    <style>
        table tr {
            padding: 40px;
            text-align: center;
        }

        table tr td {
            padding: 30px;
            /* text-align: center; */
        }
        table tr th {
            padding: 30px;
            /* text-align: center; */
        }

        body {
            font-family: 'Times New Roman', Times, serif;

        }
    </style>
</head>

<body>
    <h1>List of Orders</h1>
    <form action="" method="POST">
    <select name="filter_by_status" onchange="this.form.submit()">
        <option value="0">List by Status</option>
        <option value="paid">paid</option>
        <option value="processing">processing</option>
        <option value="dispatched">dispatched</option>
        <option value="shipped">shipped</option>
        <option value="refunded">refunded</option>

    </select>
    <form action="" method="POST">
    <select name="filter_by_date" onchange="this.form.submit()" class="dropdown">
        <option value="0">List by Date</option>
        <option value="today">Today</option>
        <option value="this_week">This Week</option>
        <option value="this_month">This Month</option>
        <option value="custom">Custom</option>

    </select>
    </form>
    <table>
        <tr>
            <th>Product ID</th>
            <th>Customer Name</th>
            <th>Quantity</th>
            <th>Status</th>
            <th>Date Ordered</th>
        </tr>
        <?php foreach ($orders as $k => $v) { ?>
            <tr>
                <td><?php echo $v->product_id ?></td>
                <td><?php echo $v->customer_name ?></td>
                <td><?php echo $v->quantity ?></td>
                <form action="" method="POST">
                    <td>
                        <input type="hidden" name="id" value=<?php echo $v->_id ?>>
                        <select name="status" id="status" onchange="this.form.submit()">
                            <option value="<?php echo $v->status ?>" selected disabled hidden><?php echo $v->status ?></option>
                            <option value="paid">paid</option>

                            <option value="processing">processing</option>
                            <option value="dispatched">dispatched</option>
                            <option value="shipped">shipped</option>
                            <option value="refunded">refunded</option>

                        </select>
                    </td>
                    <td><?php echo $v->order_date ?></td>
                </form>
            </tr>
        <?php } ?>
    </table>
</body>

</html>